"use client";

import { useState, useEffect } from "react";
import { Form, Input, Select, Button, Card, message, Space } from "antd";
import {
  SaveOutlined,
  SendOutlined,
  FileTextOutlined,
} from "@ant-design/icons";
import PostEditorWrapper from "./PostEditorWrapper";
import { Post, Category, Tag } from "@/types";

// 表单字段类型定义
interface PostFormValues {
  title: string;
  slug: string;
  summary?: string;
  coverImage?: string;
  categoryIds: string[];
  tagIds: string[];
  status: "DRAFT" | "PUBLISHED" | "ARCHIVED";
}

interface PostFormProps {
  post?: Post;
  categories: Category[];
  tags: Tag[];
  onSubmit: (values: Partial<Post>) => Promise<void>;
  onSaveDraft?: (values: Partial<Post>) => Promise<void>;
  onPreview?: (values: Partial<Post>) => void;
  loading?: boolean;
  showActions?: boolean;
}

export default function PostForm({
  post,
  categories,
  tags,
  onSubmit,
  onSaveDraft,
  onPreview,
  loading,
  showActions = true,
}: PostFormProps) {
  const [form] = Form.useForm<PostFormValues>();
  const [content, setContent] = useState(post?.content || "");
  const [isDraftSaving, setIsDraftSaving] = useState(false);
  const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(false);

  const handleSubmit = async (values: PostFormValues) => {
    try {
      await onSubmit({
        ...values,
        content,
      });
      message.success(post ? "文章更新成功" : "文章创建成功");
    } catch (error: unknown) {
      message.error(error instanceof Error ? error.message : "操作失败");
    }
  };

  const handleSaveDraft = async () => {
    if (!onSaveDraft) return;

    setIsDraftSaving(true);
    try {
      const values = await form.validateFields();
      await onSaveDraft({
        ...values,
        content,
        status: "DRAFT",
      });
      message.success("草稿保存成功");
    } catch (error: unknown) {
      if (error instanceof Error) {
        message.error(error.message);
      }
    } finally {
      setIsDraftSaving(false);
    }
  };

  const handlePreview = async () => {
    if (!onPreview) return;

    try {
      const values = await form.validateFields();
      onPreview({
        ...values,
        content,
      });
    } catch (error: unknown) {
      if (error instanceof Error) {
        message.error(error.message);
      }
    }
  };

  const generateSlug = (title: string) => {
    return title
      .toLowerCase()
      .replace(/[^\w\s-]/g, "")
      .replace(/[\s_-]+/g, "-")
      .replace(/^-+|-+$/g, "");
  };

  const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const title = e.target.value;
    // 只有在slug是自动生成的情况下才更新slug
    if (isSlugAutoGenerated) {
      const slug = generateSlug(title);
      form.setFieldsValue({ slug });
    }
  };

  const handleSlugChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const slug = e.target.value;
    // 如果用户手动修改了slug，则标记为非自动生成
    if (slug !== generateSlug(form.getFieldValue("title"))) {
      setIsSlugAutoGenerated(false);
    }
  };

  const handleSlugFocus = () => {
    // 当用户聚焦到slug字段时，如果slug是空的，则自动生成
    const currentSlug = form.getFieldValue("slug");
    const currentTitle = form.getFieldValue("title");
    if (!currentSlug && currentTitle) {
      const slug = generateSlug(currentTitle);
      form.setFieldsValue({ slug });
      setIsSlugAutoGenerated(true);
    }
  };

  useEffect(() => {
    if (post) {
      // 转换后端数据格式为前端期望的格式
      const categoryIds = post.categories?.map((cat) => cat.id) || [];
      const tagIds = post.tags?.map((tag) => tag.id) || [];

      form.setFieldsValue({
        title: post.title,
        slug: post.slug,
        summary: post.summary,
        coverImage: post.coverImage,
        status: post.status,
        categoryIds: categoryIds,
        tagIds: tagIds,
      });
      setContent(post.content);
      // 编辑模式下，slug不是自动生成的
      setIsSlugAutoGenerated(false);
    } else {
      // 创建模式下，初始时slug是自动生成的
      setIsSlugAutoGenerated(true);
    }
  }, [post, form]);

  return (
    <div className="space-y-6">
      {/* 表单头部 - 移除，因为已经在页面级别处理 */}

      <Form
        form={form}
        layout="vertical"
        onFinish={handleSubmit}
        initialValues={{
          status: "DRAFT",
          categoryIds: [],
          tagIds: [],
        }}
        className="space-y-6"
      >
        {/* 基本信息 */}
        <Card
          title={
            <div className="flex items-center space-x-2">
              <div className="w-5 h-5 bg-blue-100 rounded flex items-center justify-center">
                <FileTextOutlined className="text-blue-600 text-xs" />
              </div>
              <span className="text-gray-900 font-medium">基本信息</span>
            </div>
          }
          size="small"
          className="shadow-sm border-0"
          styles={{
            header: {
              backgroundColor: "#f8fafc",
              borderBottom: "1px solid #e2e8f0",
              padding: "16px 20px",
            },
            body: {
              padding: "20px",
            },
          }}
        >
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <Form.Item
              label={
                <span className="text-gray-700 font-medium">
                  文章标题 <span className="text-red-500">*</span>
                </span>
              }
              name="title"
              rules={[{ required: true, message: "请输入文章标题" }]}
            >
              <Input
                placeholder="请输入文章标题"
                onChange={handleTitleChange}
                size="large"
                className="rounded-lg"
              />
            </Form.Item>

            <Form.Item
              label={
                <span className="text-gray-700 font-medium">
                  URL 别名 <span className="text-red-500">*</span>
                </span>
              }
              name="slug"
              rules={[{ required: true, message: "请输入 URL 别名" }]}
            >
              <Input
                placeholder="请输入 URL 别名"
                size="large"
                className="rounded-lg"
                onChange={handleSlugChange}
                onFocus={handleSlugFocus}
                addonAfter={
                  isSlugAutoGenerated ? (
                    <span className="text-xs text-gray-500">自动生成</span>
                  ) : (
                    <span className="text-xs text-blue-500">手动编辑</span>
                  )
                }
              />
            </Form.Item>
          </div>

          <Form.Item
            label={<span className="text-gray-700 font-medium">文章摘要</span>}
            name="summary"
          >
            <Input.TextArea
              placeholder="请输入文章摘要，帮助读者快速了解文章内容"
              rows={3}
              showCount
              maxLength={200}
              className="rounded-lg"
            />
          </Form.Item>

          <Form.Item
            label={<span className="text-gray-700 font-medium">封面图片</span>}
            name="coverImage"
          >
            <Input placeholder="请输入封面图片 URL" className="rounded-lg" />
          </Form.Item>
        </Card>

        {/* 分类和标签 */}
        <Card
          title={
            <div className="flex items-center space-x-2">
              <div className="w-5 h-5 bg-green-100 rounded flex items-center justify-center">
                <span className="text-green-600 text-xs">🏷️</span>
              </div>
              <span className="text-gray-900 font-medium">分类和标签</span>
            </div>
          }
          size="small"
          className="shadow-sm border-0"
          styles={{
            header: {
              backgroundColor: "#f8fafc",
              borderBottom: "1px solid #e2e8f0",
              padding: "16px 20px",
            },
            body: {
              padding: "20px",
            },
          }}
        >
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <Form.Item
              label={
                <span className="text-gray-700 font-medium">文章分类</span>
              }
              name="categoryIds"
            >
              <Select
                mode="multiple"
                placeholder="请选择文章分类"
                className="rounded-lg"
                options={categories.map((cat) => ({
                  label: (
                    <div className="flex items-center space-x-2">
                      {cat.color && (
                        <div
                          className="w-3 h-3 rounded-full"
                          style={{ backgroundColor: cat.color }}
                        />
                      )}
                      <span>{cat.name}</span>
                    </div>
                  ),
                  value: cat.id,
                }))}
              />
            </Form.Item>

            <Form.Item
              label={
                <span className="text-gray-700 font-medium">文章标签</span>
              }
              name="tagIds"
            >
              <Select
                mode="multiple"
                placeholder="请选择文章标签"
                className="rounded-lg"
                options={tags.map((tag) => ({
                  label: (
                    <div className="flex items-center space-x-2">
                      {tag.color && (
                        <div
                          className="w-3 h-3 rounded-full"
                          style={{ backgroundColor: tag.color }}
                        />
                      )}
                      <span>{tag.name}</span>
                    </div>
                  ),
                  value: tag.id,
                }))}
              />
            </Form.Item>
          </div>
        </Card>

        {/* 发布设置 */}
        <Card
          title={
            <div className="flex items-center space-x-2">
              <div className="w-5 h-5 bg-purple-100 rounded flex items-center justify-center">
                <span className="text-purple-600 text-xs">⚙️</span>
              </div>
              <span className="text-gray-900 font-medium">发布设置</span>
            </div>
          }
          size="small"
          className="shadow-sm border-0"
          styles={{
            header: {
              backgroundColor: "#f8fafc",
              borderBottom: "1px solid #e2e8f0",
              padding: "16px 20px",
            },
            body: {
              padding: "20px",
            },
          }}
        >
          <Form.Item
            label={
              <span className="text-gray-700 font-medium">
                发布状态 <span className="text-red-500">*</span>
              </span>
            }
            name="status"
            rules={[{ required: true, message: "请选择文章状态" }]}
          >
            <Select className="rounded-lg">
              <Select.Option value="DRAFT">
                <div className="flex items-center space-x-2">
                  <div className="w-2 h-2 bg-orange-400 rounded-full"></div>
                  <span>草稿</span>
                </div>
              </Select.Option>
              <Select.Option value="PUBLISHED">
                <div className="flex items-center space-x-2">
                  <div className="w-2 h-2 bg-green-400 rounded-full"></div>
                  <span>已发布</span>
                </div>
              </Select.Option>
              <Select.Option value="ARCHIVED">
                <div className="flex items-center space-x-2">
                  <div className="w-2 h-2 bg-gray-400 rounded-full"></div>
                  <span>已归档</span>
                </div>
              </Select.Option>
            </Select>
          </Form.Item>
        </Card>

        {/* 文章内容 */}
        <Card
          title={
            <div className="flex items-center space-x-2">
              <div className="w-5 h-5 bg-indigo-100 rounded flex items-center justify-center">
                <span className="text-indigo-600 text-xs">✍️</span>
              </div>
              <span className="text-gray-900 font-medium">文章内容</span>
            </div>
          }
          size="small"
          className="shadow-sm border-0"
          styles={{
            header: {
              backgroundColor: "#f8fafc",
              borderBottom: "1px solid #e2e8f0",
              padding: "16px 20px",
            },
            body: {
              padding: "20px",
            },
          }}
        >
          <Form.Item
            name="content"
            rules={[{ required: true, message: "请输入文章内容" }]}
          >
            <PostEditorWrapper
              content={content}
              onChange={setContent}
              placeholder="请输入文章内容..."
            />
          </Form.Item>
        </Card>

        {/* 提交按钮 */}
        {showActions && (
          <Card
            size="small"
            className="shadow-sm border-0 bg-gradient-to-r from-blue-50 to-indigo-50"
            styles={{
              body: { padding: "20px" },
            }}
          >
            <div className="flex flex-col sm:flex-row justify-between items-center space-y-3 sm:space-y-0 sm:space-x-4">
              <div className="text-sm text-gray-600">
                <span className="font-medium">提示：</span>
                可以先保存草稿，稍后继续编辑和发布
              </div>
              <Space size="middle">
                <Button
                  type="default"
                  icon={<SaveOutlined />}
                  onClick={handleSaveDraft}
                  loading={isDraftSaving}
                  disabled={!content.trim()}
                  size="large"
                  className="rounded-lg border-gray-300 hover:border-blue-400"
                >
                  保存草稿
                </Button>
                <Button
                  type="primary"
                  icon={<SendOutlined />}
                  htmlType="submit"
                  loading={loading}
                  size="large"
                  className="rounded-lg bg-gradient-to-r from-blue-500 to-indigo-600 border-0 shadow-lg hover:shadow-xl"
                >
                  {post ? "更新文章" : "发布文章"}
                </Button>
              </Space>
            </div>
          </Card>
        )}
      </Form>
    </div>
  );
}
